services:
  - type: web
    name: ghostdesk
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
